spring.datasource.url=jdbc:mysql://localhost:3306/perfildb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.initialization-mode=always
spring.datasource.platform=mysql

server.address=0.0.0.0
server.port=8080